### PR TITLE
Update build system

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@Punzo You will a commit like cf91f6e  in SlicerAstro

**Comment by jcfr** [comment]
There are still few warnings described in https://github.com/SlicerIGT/SlicerIGT/issues/143

**Comment by jcfr** [comment]
To ensure `QSound` cab be found and used, this requires the following Slicer PR: https://github.com/Slicer/Slicer/pull/820

**Comment by jcfr** [comment]
Slicer PR was integrated in [r26482](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26482)

**Comment by lassoan** [comment]
Thank you Jc!

**Pull request merged**
