### PR TITLE
CollectFiducials rename to CollectPoints

### PR DESCRIPTION
**Pull request by tavaughan**

### CODE REVIEW

**Comment by tavaughan** [comment]
I've verified that this builds in Windows.
@lassoan Would you like to review, or should I go ahead and merge?

**Comment by lassoan** [comment]
Thank you! Please check the Slicer nightly dashboard tomorrow to make sure build is OK on all platforms.

**Comment by tavaughan** [comment]
Thanks. Just to be clear, this is the dashboard you are referring to?

http://slicer.cdash.org/index.php?project=Slicer4#!#Extensions-Nightly

**Comment by lassoan** [comment]
Yes, it is.

**Pull request merged**
