### PR TITLE
Move MetafileImporter module here from Sequences extension for Slicer-4.11

### PR DESCRIPTION
**Pull request by lassoan**
Sequences extension is moved to Slicer-4.11, but sequence metafile importer does not belong to Slicer core, therefore it is moved here.

### CODE REVIEW

**Comment by jamesobutler** [comment]
@lassoan Why does Sequence Metafile importer not belong in Slicer core with the other sequence work? I currently use the Sequences extension and also specifically use this importer. I haven’t required any of the rest of SlicerIGT before.

**Comment by lassoan** [comment]
Sequence metafile (tracked image data) format is specific to SlicerIGT. Moving it to Slicer core would make the core slightly larger and make the feature harder to modify in stable versions. Maybe we could move it to SlicerIGSIO extension, that is much smaller than SlicerIGT.

**Comment by jamesobutler** [comment]
Yeah I think SlicerIGSIO would make sense as there is a SequenceIO module already there too. We use it for reading some PLUS captured tracked meta image files.

**Comment by jamesobutler** [comment]
Also I guess SlicerIGSIO and other extensions will need to update their dependencies once Sequences gets merged into Slicer core.

**Comment by lassoan** [comment]
We may keep an empty Sequences extension around for a while to avoid breaking builds (it could just contain a single scripted module that logs a warning that sequences is deprecated, maybe also create an alias of slicer.modules.sequencebrowser to slicer.modules.sequences).

**Comment by jamesobutler** [comment]
@lassoan did you not want to add it to SlicerIGSIO?

**Comment by lassoan** [comment]
Yes, I'll add metafileimporter to SlicerIGSIO.

**Comment by lassoan** [comment]
Done - https://github.com/IGSIO/SlicerIGSIO/commit/351741a58d173ce81b084ccfedf2628fccaaddc7

**Pull request merged**
